apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  namespace: migration
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:6.4.4
          args:
            - info
            - repair
            - migrate
            - info
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://10.0.2.15:5432/jpetstore
            - name: FLYWAY_USER
              value: admin
            - name: FLYWAY_PASSWORD
              value: admin
            - name: FLYWAY_PLACEHOLDER_REPLACEMENT
              value: "true"
            - name: FLYWAY_PLACEHOLDERS_USERNAME
              value: admin
            - name: FLYWAY_PLACEHOLDERS_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: /flyway/sql
              name: sql
      volumes:
        - name: sql
          persistentVolumeClaim:
            claimName: flyway-pv-claim
      restartPolicy: Never
